### ISSUE TITLE
Configure responsive layout

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#11]
Code page, CSS to respond to viewports on monitors and smartphones. Tablets optional

**Comment by ratulkhan74** [comment]
responsive done for these four sections
header
hero
contact us
footer

**Comment by stratofax** [comment]
@ratulkhan74 Please proceed with the remaining sections

**Comment by stratofax** [comment]
@ratulkhan74 I've enclosed annotated screen shots to depict issues around the responsive layout for the sections you've worked on so far with sample screens for smartphones and tablets:

![Screenshot_2023-07-06_at_17-25-41_C_Baily_Law_LLC](https://github.com/stratofax/cbailylaw/assets/37887507/381558d0-c596-4849-8692-923297cf85b6)
![Screenshot_2023-07-06_at_17-27-06_C_Baily_Law_LLC](https://github.com/stratofax/cbailylaw/assets/37887507/8a1158b0-a92b-492e-a59c-c141a16df9c9)

**Comment by ratulkhan74** [comment]
All responsive issues are fixed

**Comment by ratulkhan74** [comment]
already fixed

**Comment by stratofax** [comment]
This issue will close automatically when I merge PR #43

**Comment by stratofax** [comment]
@ratulkhan74 This is why we don't close issues until merge! There are some problems with the Hero section. Please see the enclosed screenshots.
![Screenshot 2023-07-07 at 18-15-40 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/7ddbad82-78c1-457f-8cc4-b5f8ec01654c)
![Screenshot 2023-07-07 at 18-16-35 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/24f27b62-b5db-4830-bd19-73ab0276e2b8)
![Screenshot 2023-07-07 at 18-17-04 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/7eaf05c0-0ed9-4aa8-a1a7-5bd723098599)

**Comment by stratofax** [comment]
@ratulkhan74 Also the photo in the About section is compressing horizontally before the tablet breakpoint is reached.

Before compression
![Screenshot 2023-07-07 at 18-22-49 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/5c9cc00a-1b01-486b-b0d2-c8f545c4efc7)

After compression
![Screenshot 2023-07-07 at 18-23-14 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/1e893ed5-b98e-445c-b61b-7f65c9c5dd5e)

**Comment by stratofax** [comment]
This is substantially complete. There are some minor fixes required, but I'll address them in separate issues for post launch.
