### ISSUE TITLE
Fix Services "see more..." link behavior

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#12]
* When you click on the "see more..." link, the page also scrolls to the point where the new text is revealed. No scrolling! Keep the page from moving
* When the hidden text appears, the "see more..." link should vanish.
* Can we reveal the text on a mouse over as well?

See the annotated screenshot for details:
![Annotated_Screenshot_2023-06-30_at_01-12-00_C_Baily_Law_LLC](https://github.com/stratofax/cbailylaw/assets/37887507/a2102b1e-58db-4191-9ec4-337efd9cda63)

**Comment by ratulkhan74** [comment]
fixed see more button issues

**Comment by stratofax** [comment]
Also, In Progress until merge

**Comment by stratofax** [comment]
Great job!
