### ISSUE TITLE
Our Services Icons need transparent backgrounds

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#13]
Only the "Medical-Use Cannabis" icon has a transparent background. Consider asking Johan. See attatched illustration
![Annotated_Screenshot_2023-06-30_at_01-34-43_C_Baily_Law_LLC](https://github.com/stratofax/cbailylaw/assets/37887507/93fbefb2-6fa4-4c43-b80d-b155ee0c263f)

**Comment by ratulkhan74** [comment]
I have fixed with css i think don't need to bother Johan

**Comment by stratofax** [comment]
I'll also mark this as "In progress" and close it with a merge.

**Comment by stratofax** [comment]
This is improved. I'm going to open a new post-launch issue regarding "dark mode"
