### ISSUE TITLE
Fix spacing and alignment in Testimonials section

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#17]
* Attribution line should be right- aligned
* Too much space below each card

![Annotated_Screenshot_2023-07-05_at_22-13-34_C_Baily_Law_LLC](https://github.com/stratofax/cbailylaw/assets/37887507/19c77c60-9aba-48a9-92f9-e0c30dca3fdd)

**Comment by ratulkhan74** [comment]
spacing issues fixed

**Comment by stratofax** [comment]
I'm going to reopen this issue and mark it as "In Progress"

**Comment by stratofax** [comment]
@ratulkhan74 You've resolved the spacing issues: nice work! There are still some font issues, though, but I'll create a new issue for post launch.
