### ISSUE TITLE
Select a new picture for the hero section

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#27]
From the client:

"Some feedback I received on the picture is that I do not look too confident due to my arms being down by my side. I tend to agree. 

If you enlarge the picture to shorten my arms, would that make it better? 

Alternatively, I think I look more confident in the other picture"

This photo is: Christine_Baily_14DS3.jpeg

Enclosed: Orignal, flipped horzontal, background removed; cropped.

Please use the enclosed cropped version

![Christine_Baily_14DS3-crop2](https://github.com/stratofax/cbailylaw/assets/37887507/93957faf-0ff6-4b5c-8280-8efe87c9ff94)

**Comment by stratofax** [comment]
@ratulkhan74 To improve SEO, please rename the image enclosed above as follows `c_baily_shoulders.png" and preserve the edited `alt` tag.

**Comment by ratulkhan74** [comment]
hero image changed

**Comment by stratofax** [comment]
I'm not seeing this change, unfortunately. I think it's because you renamed the new image and the old image is cached in my browser.

**Comment by stratofax** [comment]
Yes, my browser caches images based on the file name, not the contents. To avoid this issue in the future, please don't replace images with the same file name, but add a new image and update the reference in the html file.
