### ISSUE TITLE
Add space below paragraphs

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#31]
Block paragraphs (with no first line indent) should have a line space below.

**Comment by stratofax** [comment]
I noticed this problem when I added a paragraph to the about section

**Comment by ratulkhan74** [comment]
which section's paragraph i have to add space?

**Comment by stratofax** [comment]
The About section. Moving this to post-launch.

**Comment by stratofax** [comment]
Closed with PR #49
