### ISSUE TITLE
Italics and links are too small in Testimonials section

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#36]
Italics (`<em>`) text and hyperlink text (`<a>`) renders in a smaller point size than regular (plain) text. Adjust so this tag text inherits the same font size as plain text.

![Annotated_Screenshot_2023-07-05_at_22-13-34_C_Baily_Law_LLC](https://github.com/stratofax/cbailylaw/assets/37887507/19c77c60-9aba-48a9-92f9-e0c30dca3fdd)

**Comment by stratofax** [comment]
The _italics_ type seems to grow as the viewport shrinks!

**Comment by stratofax** [comment]
The hyperlink issue is resolved, but the italics are too small at full size and too large for smartphone viewports

![Screenshot 2023-07-07 at 19-09-45 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/b73d4308-69bf-463d-ad21-cd08745dad48)

**Comment by stratofax** [comment]
Italics (`em`) should inherit the font size from the containing `p` tag. As you shrink the `p` tag text for the smartphone viewport, the `em` tag remains the same (larger) size:

![Screenshot 2023-07-08 at 4 04 01 PM](https://github.com/stratofax/cbailylaw/assets/37887507/ed1eb140-36c0-4d10-8a08-cdc549a4b894)

**Comment by ratulkhan74** [comment]
fixed

**Comment by stratofax** [comment]
Done on PR #49
