### ISSUE TITLE
Remove class prefix from HTML and CSS files

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#39]
Remove the `cbailylaw__`class prefix from the CSS and HTML files, for two reasons: 

- File size: the style.css file is 14,530 bytes so almost 10% (1,232 bytes) is just the same string over and over again.
- Readability: It's very hard to inspect the page in the developer tools because "cbailylaw__" takes up so much space

**Comment by ratulkhan74** [comment]
done

**Comment by stratofax** [comment]
Thank you, this makes the code much easier to read and follow
