### ISSUE TITLE
Extend About section

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#41]
Add another row to the About section, with the green background, white text, with two columns.

Column 1 (below photo)

## Experience

- General Counsel, Massachusetts Cannabis Control Commission, Worcester & Boston, MA. February 2018 to July 2023.
- Senior Staff Counsel, Office of the Chief Staff Counsel, Massachusetts Supreme Judicial Court, Boston. MA, February 2012 to February 2018.
- Assistant Attorney General, Massachusetts Office of the Attorney General, Boston, MA. January 2004 to January 2012.  
- Litigation Associate, Day, Berry & Howard LLP, Hartford, CT & Boston, MA. September 2000 to December 2003.
- Law Clerk to the Chief Justice and two Associate Justices, Connecticut Supreme Court, Hartford, CT. June 1999 to August 2000.

Column 2 (below About text)

## Education

- Western New England University School of Law, J.D. cum laude awarded in 1999.
- Clark University, M.A. Developmental Psychology awarded in 1994.  Also completed coursework toward a doctoral degree. 
- Rutgers University, B.A. in English & Psychology, highest honors, awarded in 1990.

**Comment by stratofax** [comment]
@ratulkhan74 Great job starting this! The client wants this to be part of the site launch.

**Comment by ratulkhan74** [comment]
about section extension has been added

**Comment by stratofax** [comment]
Nice work! Posted to https://cbailylawwebsite--stage-c8yvdfny.web.app/

@ratulkhan74 please open a PR for this and any other updates you may have added to your active branch since I closed the last PR

**Comment by stratofax** [comment]
Nice work, closed
