### ISSUE TITLE
Add "Recognition" menu item for "Testimonials" section

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#45]
I removed the Testimonial menu last week while we were working on the layout of that section. Now that the layout is ready, I realized we need to restore the menu, but also maybe choose a better word. I'll ask the client to select one.

Here are some more general options that cover both Testimonials and Press. 

-  Endorsements
-  Recommendations
-  Commendations
-  Recognition
-  Acclaim
-  Appreciation

**Comment by ratulkhan74** [comment]
added menu item for testimonial

**Comment by stratofax** [comment]
Sorry, I only updated the subject of this issue and wasn't very clear. The menu item should read:

```
Recognition
```

instead of "Recommendations"

**Comment by stratofax** [comment]
Footer menu should also have a "Recognition" item

**Comment by ratulkhan74** [comment]
changes done in menu

**Comment by stratofax** [comment]
Closed with PR #49
