### ISSUE TITLE
Hero image is floating above the border of the hero section

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#46]
At larger resolutions, the hero image floats over the border of the hero section. See below:
![Screenshot 2023-07-07 at 19-25-40 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/f3717567-d433-4efb-b2e4-b8a03cfd2ae5)

**Comment by ratulkhan74** [comment]
hero image floating issue fixed

**Comment by stratofax** [comment]
Well done!
