### ISSUE TITLE
Adjust images for "dark mode"

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#47]
Some people like to browse the web in "dark mode." In general, this site looks remarkably good. However, notice how the images in the Services section are difficult to see, and the background image in Testimonials is not transparent.

![Screenshot 2023-07-07 at 19-14-06 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/d55efef6-1cf3-4fe8-9678-b39c1be2dd6b)

**Comment by ratulkhan74** [comment]
for this change i need png images

**Comment by ratulkhan74** [comment]
done

**Comment by stratofax** [comment]
Thank you for working directly with Johan on this, looks great!
