### ISSUE TITLE
About image distorts horizontally at some resolutions

### ISSUE THREAD

**Issue by stratofax** [stratofax/cbailylaw#48]
Just before the tablet breakpoint, the portrait image squeezes horizontally. Both width and height should scale proportionally.

![Screenshot 2023-07-07 at 18-22-49 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/ffd7b33c-4aba-42dd-a4c1-e2430d631358)

![Screenshot 2023-07-07 at 18-23-14 C Baily Law LLC](https://github.com/stratofax/cbailylaw/assets/37887507/0bc14ca5-f914-4fc7-820a-1f66c1f63e75)

**Comment by ratulkhan74** [comment]
about section image issue fixed

**Comment by stratofax** [comment]
This looks good!
